;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Geometry and lifecycle checks at the compositor primitive boundary.
(use-modules (srfi srfi-1))
(define placements (make-hash-table))
(define border #f)
(define transients '())
(define transient-queries 0)
(define (wm-transient-ids)
  (set! transient-queries (+ transient-queries 1)) transients)
(define (wm-place-window id x y w h)
  (hash-set! placements id (list x y w h)) #t)
(define (wm-focus-rect x y w h) (set! border (list x y w h)) #t)
(define (wm-focus-window id) #t)
(define (wm-clear-focus) #t)
(define (wm-set-fullscreen id on) #t)
(define (wm-log message) #t)
(define (wm-message . args) #t)
(use-modules (minde compositor frames) (minde groups))
(define (expect name actual expected)
  (unless (equal? actual expected) (error name actual expected)))
(define (rect id) (hash-ref placements id))
(define (setting key) (assq-ref (gap-settings) key))
(handle-heads-change! '((10 0 0 1000 800)))
(handle-window-map! 1 "one" "test")
(expect "disabled initially" (setting 'enabled?) #f)
(expect "default geometry" (rect 1) '(3 3 994 794))
(expect "no metadata work when disabled" transient-queries 0)
(configure-gaps! #:inner 5 #:outer 10 #:head 20)
(expect "configuration does not enable" (rect 1) '(3 3 994 794))
(gaps-on!)
(expect "head inset" (heads) '((10 20 20 960 760)))
(expect "single window retains all padding" (rect 1) '(38 38 924 724))
(expect "border outside content" border '(35 35 930 730))
(define enabled-rect (rect 1))
(define queries transient-queries)
(gaps-on!)
(expect "enable is idempotent" transient-queries queries)
(do ((n 0 (+ n 1))) ((= n 5)) (gaps-off!) (gaps-on!))
(expect "toggle has no cumulative head shrink" (rect 1) enabled-rect)
(split-frame-horizontal!)
(expect "empty split still gets gaps" (rect 1) '(38 38 454 724))
(focus-next-frame!)
(handle-window-map! 2 "two" "test")
(expect "right split" (rect 2) '(508 38 454 724))
(expect "inner distance includes two border reservations"
        (- (car (rect 2)) (+ (car (rect 1)) (caddr (rect 1)))) 16)
(configure-gaps! #:inner 3)
(expect "odd inner padding is exact" (rect 2) '(506 36 458 728))
(expect "omitted settings retained" (setting 'head) 20)
(define before (gap-settings))
(for-each
 (lambda (bad)
   (expect "invalid candidate throws"
           (catch #t (lambda () (configure-gaps! #:inner 7 #:head bad) #f)
             (lambda args #t)) #t)
   (expect "invalid candidate leaves settings intact" (gap-settings) before))
 (list -1 2.5 2.0 'bad))
(set! transients '(2))
(set! transient-queries 0)
(sync-frames!)
(expect "one transient query per sync" transient-queries 1)
(expect "transient skips inner/outer but retains head layout" (rect 2) '(503 23 474 754))
(expect "transient border agrees" border '(500 20 480 760))
(set! transients '())
(sync-frames!)
(fullscreen!)
(hash-clear! placements)
(configure-gaps! #:inner 6)
(expect "gap changes do not configure fullscreen clients" (hash-count (const #t) placements) 0)
(fullscreen!)
(expect "fullscreen exit applies pending gap settings" (rect 2) '(509 39 452 722))
;; Switching away and back must keep hidden groups and every head sized.
(switch-to-next-group!)
(handle-window-map! 3 "three" "test")
(configure-gaps! #:head 30)
(switch-to-previous-group!)
(expect "hidden group resizes" (rect 2) '(509 49 442 702))
(handle-heads-change! '((10 -1000 30 1000 770) (11 0 0 800 600)))
(expect "negative origins and bar reservation" (car (heads)) '(10 -970 60 940 710))
(focus-next-head!)
(handle-window-map! 4 "four" "test")
(expect "second output border uses its own bounds" border '(46 46 708 508))
(move-focus! 'left)
(expect "directional focus crosses head gap" (current-head-id) 10)
(handle-heads-change! '((10 -1000 30 1000 770)))
(expect "removed output adopted" (length (heads)) 1)
(set-gaps! 10 6)
(expect "legacy removes head inset" (heads) '((10 -1000 30 1000 770)))
(expect "legacy mode" (setting 'mode) 'legacy)
(configure-gaps! #:inner 100000 #:outer 100000 #:head 100000)
(for-each
 (lambda (p)
   (when (>= (car p) -1000)
     (unless (and (> (caddr p) 0) (> (cadddr p) 0))
       (error "positive client dimensions" p))))
 (hash-map->list (lambda (id p) p) placements))
(gaps-off!)
(expect "oversized request does not corrupt raw heads" (heads) '((10 -1000 30 1000 770)))
(configure-gaps! #:inner 0 #:outer 0 #:head 0)
(gaps-on!)
(expect "zero sizes preserve output bounds" (heads) '((10 -1000 30 1000 770)))
;; Floats are not resized or moved when head padding changes.
(float-this!)
(set-float-geometry! (focused-window-id) '( -900 100 300 200))
(define float-before (float-geometry (focused-window-id)))
(configure-gaps! #:head 40)
(expect "head changes preserve floating geometry"
        (float-geometry (focused-window-id)) float-before)
;; Span mode gets one inset around the synthetic bounding rectangle.
(handle-heads-change! '((10 -1000 0 1000 800) (11 0 0 1000 800)))
(set-heads-mode! 'span (list (current-group)))
(expect "span inset once around union" (heads) '((10 -960 40 1920 720)))
(gaps-off!)
(expect "span off restores union" (heads) '((10 -1000 0 2000 800)))
;; Direct safety checks cover tiny rectangles and asymmetric odd padding.
(define inset (@@ (minde compositor frames) inset-gap-rect))
(expect "tiny frame keeps original positive size" (inset '(10 20 3 2) 99 99 99 99)
        '(10 20 3 2))
(expect "oversized asymmetric padding stays inside" (inset '(0 0 10 10) 100 0 200 0)
        '(1 0 7 10))
(display "gaps: all checks passed\n")
