;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Observe batches at the primitive boundary, including cache invalidation.
(use-modules (minde compositor frames))
(define last-batch #f)
(define rejected '())
(define (wm-place-windows placements)
  (set! last-batch placements)
  rejected)
(define place! (@@ (minde compositor frames) apply-placements!))
(define (expect description actual expected)
  (unless (equal? actual expected) (error description actual expected)))
(define original '(1 10 20 300 400 #t))
(place! (list original))
(expect "first placement is sent" last-batch (list original))
(place! (list original))
(expect "unchanged rectangle is skipped" last-batch '())
(for-each
 (lambda (changed)
   (place! (list changed))
   (expect "each changed coordinate is sent" last-batch (list changed))
   (place! (list original)))
 '((1 11 20 300 400 #t) (1 10 21 300 400 #t)
   (1 10 20 301 400 #t) (1 10 20 300 401 #t)))
(define floating '(1 10 20 300 400 #f))
(place! (list floating))
(place! (list floating))
(expect "floating placement is always sent" last-batch (list floating))
(place! (list original))
(expect "floating placement invalidates tiled cache" last-batch (list original))
(set! rejected '(2))
(define missing '(2 10 20 300 400 #t))
(expect "unknown IDs are returned" (place! (list missing)) '(2))
(set! rejected '())
(place! (list missing))
(expect "failed placement is retried" last-batch (list missing))
(display "placement cache: all checks passed\n")
