;;; SPDX-License-Identifier: GPL-3.0-or-later
;;;
;;; GitHub Pages source config. Built by .github/workflows/pages.yml via
;;; `guix shell -m doc/manifest.scm -- haunt build`, run with doc/ as the
;;; working directory. Haunt is Guile Scheme, the same language Minde's
;;; own policy layer and generator scripts (scripts/generate-docs et al.)
;;; are written in, so this needs no toolchain beyond what the project
;;; already carries in `guix shell -m manifest.scm`.
;;;
;;; doc/*.md and doc/generated/*.md each render to one page, title taken
;;; from the file's first `# Heading`. No front matter is required, so the
;;; doc files themselves stay untouched -- they're read elsewhere too, e.g.
;;; tests/check-doc-links.sh, and shouldn't carry site-only metadata.
;;; doc/generated/{manual.html,demo-manifest.json,api-catalog.scm} are
;;; copied through verbatim by `static-directory`.
;;;
;;; `docs-pages' below is a from-scratch replacement for Haunt's stock
;;; `flat-pages' builder: that builder scans its directory using only
;;; `site-file-filter' (dotfiles/temp-file exclusion), not a reader-aware
;;; extension check, so it hands every non-Markdown file it meets -- the
;;; generated .scm/.json/.html assets -- to `reader-find', which returns
;;; #f, and `flat-pages' calls `reader-read' on that #f and crashes rather
;;; than skipping it (its own `(#f (error ...))' fallback clause is dead
;;; code: the preceding `reader' pattern is an unconstrained variable and
;;; matches #f too). Filtering to ".md" during the directory walk itself,
;;; before any reader is involved, sidesteps that.

(use-modules (commonmark)
             (haunt artifact)
             (haunt builder assets)
             (haunt html)
             (haunt site)
             (ice-9 ftw)
             (ice-9 match)
             (ice-9 textual-ports)
             (srfi srfi-1)
             (srfi srfi-13))

(define (flatten-strings tree)
  "Depth-first list of every string leaf under TREE, so inline markup
(code spans, emphasis) inside a heading still contributes its text."
  (match tree
    ((? string? s) (list s))
    ((? pair? nodes) (append-map flatten-strings nodes))
    (_ '())))

(define (first-heading-text tree)
  "Return the flattened text of the first h1 node found anywhere in the
commonmark SXML TREE, or #f if there is none."
  (match tree
    (('h1 rest ...) (string-join (flatten-strings rest) ""))
    ((? pair? nodes) (any first-heading-text nodes))
    (_ #f)))

(define (page-title file-name body)
  (or (first-heading-text body)
      (basename file-name ".md")))

(define %github-blob-prefix
  "https://github.com/9s-l-s9/minde/blob/main/")

(define (rewrite-href href)
  "Doc source files link to each other by their source name, e.g.
\"tutorial.md\" or \"generated/api-reference.md#anchor\" -- the same links
tests/check-doc-links.sh resolves against files on disk. Once rendered,
each of those targets is instead an .html page at the same path, so local,
non-fragment-only links ending in .md are rewritten to .html here.

A handful of doc/*.md files also link out to repo-root files (../SECURITY.md,
../README.md#...) that are never part of this site -- those go to their
GitHub blob view instead, so the link still resolves rather than 404ing."
  (if (or (string-null? href)
          (string-prefix? "#" href)
          (string-prefix? "http://" href)
          (string-prefix? "https://" href)
          (string-prefix? "mailto:" href))
      href
      (let* ((hash (string-index href #\#))
             (path (if hash (substring href 0 hash) href))
             (fragment (if hash (substring href hash) "")))
        (cond
         ((string-prefix? "../" path)
          (string-append %github-blob-prefix (substring path 3) fragment))
         ((string-suffix? ".md" path)
          (string-append (substring path 0 (- (string-length path) 3))
                         ".html" fragment))
         (else href)))))

(define (rewrite-md-links tree)
  (match tree
    (('a ('@ attrs ...) body ...)
     `(a (@ ,@(map (match-lambda
                     ((k v) (if (eq? k 'href) (list k (rewrite-href v)) (list k v))))
                   attrs))
         ,@(map rewrite-md-links body)))
    ((? pair? nodes) (map rewrite-md-links nodes))
    (other other)))

(define (strip-generator-comments text)
  "Drop standalone HTML-comment lines (the `<!-- Generated by ... -->'
markers scripts/generate-docs et al. stamp on generated files). This
project's vendored guile-commonmark (0.1.2) has no HTML-block support and
raises \"unknown node\" on them; the doc files themselves are left alone,
this only affects what gets fed to the renderer."
  (string-join
   (remove (lambda (line)
             (and (string-prefix? "<!--" (string-trim line))
                  (string-suffix? "-->" (string-trim-right line))))
           (string-split text #\newline))
   "\n"))

;; guile-commonmark 0.1.2 implements plain CommonMark only, not the GFM
;; pipe-table extension the generated reference docs use (e.g.
;; doc/generated/api-reference.md). Left alone, a table becomes one <p> of
;; inline-parsed text with "\n" between rows and literal "|" characters --
;; readable but not a table. table-paragraph->table below reassembles it
;; into a real <table> from that already inline-parsed content, so code
;; spans/emphasis inside cells still render correctly; it does not handle a
;; literal "|" inside a cell's own text (none of this project's docs have
;; one).

(define (soft-break? node)
  (and (string? node) (string=? node "\n")))

(define (split-on-newline-string children)
  "Split CHILDREN, a paragraph's mixed string/element children, into a list
of per-line child-lists wherever an exact \"\\n\" string node (a soft line
break) occurs."
  (let loop ((children children) (line '()) (lines '()))
    (cond
     ((null? children) (reverse (cons (reverse line) lines)))
     ((soft-break? (car children))
      (loop (cdr children) '() (cons (reverse line) lines)))
     (else
      (loop (cdr children) (cons (car children) line) lines)))))

(define (looks-like-table-row? line)
  "LINE is a per-line child-list. True if it opens and closes with a bare
\"|\"-bearing string, i.e. it came from a source line starting and ending
with a pipe."
  (match line
    (((? string? first) rest ...)
     (and (string-prefix? "|" (string-trim first))
          (match (last-pair line)
            (((? string? last)) (string-suffix? "|" (string-trim-right last)))
            (_ #f))))
    (_ #f)))

(define (split-row-on-bar line)
  "Split one row's child-list on top-level \"|\" characters inside its
string children, dropping the empty leading/trailing cells the row's own
enclosing bars produce."
  (define (flush cell cells) (cons (reverse cell) cells))
  (let loop ((line line) (cell '()) (cells '()))
    (cond
     ((null? line) (reverse (flush cell cells)))
     ((string? (car line))
      (let piece-loop ((pieces (string-split (car line) #\|)) (cell cell) (cells cells))
        (cond
         ((null? (cdr pieces))
          (loop (cdr line) (cons (car pieces) cell) cells))
         (else
          (piece-loop (cdr pieces) '() (flush (cons (car pieces) cell) cells))))))
     (else
      (loop (cdr line) (cons (car line) cell) cells)))))

(define (trim-cell cell)
  "Trim leading whitespace off CELL's first child and trailing whitespace
off its last, when those children are strings; interior structure (code
spans, emphasis) is left untouched."
  (match cell
    (() '())
    ((only)
     (if (string? only) (list (string-trim-both only)) (list only)))
    ((first middle ... last)
     (append (list (if (string? first) (string-trim first) first))
             middle
             (list (if (string? last) (string-trim-right last) last))))))

(define (separator-row? cells)
  (every (lambda (cell)
           (match cell
             (((? string? s))
              (string-every (lambda (c) (or (char=? c #\-) (char=? c #\:)
                                            (char-whitespace? c)))
                            s))
             (_ #f)))
         cells))

(define (row-cells line)
  "Cells of one table row, with the empty leading/trailing artifacts the
row's own enclosing \"|\" characters produce in `split-row-on-bar' dropped."
  (let ((cells (split-row-on-bar line)))
    (map trim-cell (drop-right (drop cells 1) 1))))

(define (table-paragraph->table children)
  "Given a <p>'s CHILDREN, return a <table> sxml node if they form a
pipe table, or #f otherwise."
  (define lines (split-on-newline-string children))
  (and (>= (length lines) 2)
       (every looks-like-table-row? lines)
       (let* ((rows (map row-cells lines))
              (header (car rows))
              (rest (cdr rows)))
         (and (pair? rest) (separator-row? (car rest))
              `(table
                (thead (tr ,@(map (lambda (cell) `(th ,@cell)) header)))
                (tbody ,@(map (lambda (row) `(tr ,@(map (lambda (cell) `(td ,@cell)) row)))
                              (cdr rest))))))))

(define (render-tables tree)
  (match tree
    (('p children ...)
     (or (table-paragraph->table children)
         `(p ,@(map render-tables children))))
    ((? pair? nodes) (map render-tables nodes))
    (other other)))

(define* (docs-pages directory #:key template (prefix "/"))
  "Render every .md file under DIRECTORY to an .html page at the mirrored
path under PREFIX, title taken from its first heading."
  (lambda (site posts)
    (define (enter? file-name stat memo) #t)
    (define (noop file-name stat memo) memo)
    (define (leaf file-name stat memo)
      (if (string-suffix? ".md" file-name) (cons file-name memo) memo))
    (define (err file-name stat errno memo)
      (error "doc page directory scan failed" file-name errno))
    (define src-files
      (file-system-fold enter? leaf noop noop noop err '() directory))
    (map (lambda (file-name)
           (call-with-input-file file-name
             (lambda (in-port)
               (define port
                 (open-input-string
                  (strip-generator-comments (get-string-all in-port))))
               (let* ((body (render-tables (rewrite-md-links (commonmark->sxml port))))
                      (title (page-title file-name body))
                      (dir (substring (dirname file-name)
                                      (string-length directory)))
                      (out (string-append prefix dir
                                          (if (string-null? dir) "" "/")
                                          (basename file-name ".md") ".html")))
                 (serialized-artifact out (template site title body) sxml->html)))))
         src-files)))

(define (page-template site title body)
  `((doctype "html")
    (html (@ (lang "en"))
     (head
      (meta (@ (charset "utf-8")))
      (meta (@ (name "viewport") (content "width=device-width,initial-scale=1")))
      (title ,(if (string=? title (site-title site))
                  title
                  (string-append title " — " (site-title site))))
      (style "
:root{--bg:#fff;--ink:#0a0a0a;--muted:#565656;--soft:#d4d4d4}
@media(prefers-color-scheme:dark){:root{--bg:#0a0a0a;--ink:#ededed;--muted:#a0a0a0;--soft:#333}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
     font:15px/1.6 ui-monospace,'IBM Plex Mono',monospace}
.page{width:min(760px,calc(100% - 32px));margin:0 auto;padding:24px 0 60px}
nav{font-size:12px;letter-spacing:.06em;text-transform:uppercase;
    border-bottom:2px solid var(--ink);padding-bottom:10px;margin-bottom:20px}
nav a{color:inherit}
h1,h2,h3{line-height:1.2}
h1{border-bottom:1px solid var(--soft);padding-bottom:8px}
a{color:inherit;text-underline-offset:2px}
pre{background:color-mix(in srgb,var(--ink) 6%,var(--bg));
    padding:10px 12px;overflow-x:auto}
code{font-family:inherit}
table{border-collapse:collapse;width:100%}
th,td{border-bottom:1px solid var(--soft);padding:5px 8px;text-align:left}
footer{margin-top:40px;padding-top:10px;border-top:1px solid var(--soft);
       font-size:12px;color:var(--muted)}"))
     (body
      (div (@ (class "page"))
       (nav (a (@ (href "/index.html")) ,(site-title site)))
       ,body
       (footer "Generated documentation; source lives in doc/ of the "
               (a (@ (href ,(string-append "https://" (site-domain site))))
                  "Minde")
               " repository."))))))

(site #:title "Minde"
      #:domain "github.com/9s-l-s9/minde"
      #:builders (list (docs-pages "." #:template page-template)
                       (static-directory "generated"))
      #:build-directory "_site")
