#!/bin/sh
exec guile --no-auto-compile -L scheme -s "$0" "$@"
!#
;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Load the portable configuration with inert compositor operations and print
;;; the resulting live key tables. No key sequence is copied into this file.

(use-modules (srfi srfi-1)
             (srfi srfi-13))

(define (wm-spawn command) #t)
(define (wm-quit) #t)
(define (wm-log message) #t)
(define (wm-place-window . arguments) #t)
(define (wm-focus-window . arguments) #t)
(define (wm-close-window . arguments) #t)
(define (wm-clear-focus) #t)
(define (wm-output-geometry) '(0 0 1280 720))
(define (wm-message . arguments) #t)
(define (wm-run-after-ms . arguments) #t)
(define (wm-set-fullscreen . arguments) #t)
(define (wm-kill-window . arguments) #t)
(define (wm-warp-pointer . arguments) #t)
(define (wm-request-paste) #t)
(define (wm-set-clipboard . arguments) #t)
(define (wm-border-color . arguments) #t)
(define (wm-add-overlay . arguments) #t)
(define (wm-clear-overlays) #t)
(define (wm-send-key . arguments) #t)
(define (wm-warp-pointer-relative . arguments) #t)
(define (wm-set-key-repeat . arguments) #t)

(setenv "MINDE_RULES_FILE" "/nonexistent-minde-rules.scm")
(setenv "MINDE_CONFIG" "scheme/default-config.scm")
(unsetenv "MINDE_TERMINAL")
(unsetenv "MINDE_FULL_KEYMAP")
(unsetenv "MINDE_E2E_LEGACY_KEYMAP")
(fluid-set! %file-port-name-canonicalization 'absolute)
(primitive-load (canonicalize-path "scheme/init.scm"))

(define (sorted-keys table)
  (sort (hash-map->list (lambda (key value) key) table) string<?))

(define (walk-keymap keymap path)
  (append-map
   (lambda (key)
     (let* ((value (hash-ref keymap key))
            (child (or (binding-submap keymap key)
                       (and (hash-table? value) value)))
            (sequence (append path (list key)))
            (description (or (binding-doc keymap key) "undocumented binding"))
            (entry (list sequence description (if child "submap" "action"))))
       (cons entry (if child (walk-keymap child sequence) '()))))
   (sorted-keys keymap)))

(define (display-sequence sequence)
  (string-join sequence " "))

(display "# Generated default keymap reference\n\n")
(display "<!-- Generated by scripts/generate-keymap-reference.scm; do not edit. -->\n\n")
(format #t "The repository default prefix is `~a`. Personal Guix Home configuration may deliberately replace it (for example with `Print`); this page describes the dependency-light repository default loaded from `scheme/init.scm` and `scheme/default-config.scm`.\n\n"
        (key-spec %prefix-mods %prefix-key))

(display "## Direct bindings\n\n")
(display "| Sequence | Description |\n|---|---|\n")
(for-each
 (lambda (binding)
   (let ((spec (car binding)))
     (format #t "| `~a` | ~a |\n"
             (key-spec (car spec) (cdr spec))
             (or (hash-ref %global-binding-docs spec) "undocumented binding"))))
 (sort (hash-map->list (lambda (spec value) (cons spec value)) %keybindings)
       (lambda (left right)
         (string<? (key-spec (caar left) (cdar left))
                   (key-spec (caar right) (cdar right))))))

(display "\n## Prefix bindings\n\n")
(display "| Sequence after prefix | Description | Kind |\n|---|---|---|\n")
(display "| `?` | show contextual help and keep the current map armed | action |\n")
(for-each
 (lambda (entry)
   (format #t "| `~a` | ~a | ~a |\n"
           (display-sequence (car entry)) (cadr entry) (caddr entry)))
 (walk-keymap %prefix-bindings '()))
