#!/bin/sh
exec guile --no-auto-compile -L scheme -L tools/guile-autodoc -s "$0" "$@"
!#
;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Generate the public Scheme binding inventory from live Guile interfaces.
;;;
;;; The per-module bindings tables (name, kind, signature, docstring, a
;;; link to the exact source line) are generic to any Guile project and
;;; live in tools/guile-autodoc (github.com/9s-l-s9/guile-autodoc,
;;; vendored as a submodule) -- pulled out from an earlier version of this
;;; script so the same source-scanning and doc-to-code linking logic isn't
;;; maintained twice. Only what's specific to Minde stays here: the
;;; %api-binding-documentation convention (see below), the Demonstration
;;; column sourced from the command catalog, and the "Registered commands"
;;; table.

(use-modules (srfi srfi-1)
             (srfi srfi-13)
             (autodoc scan)
             (autodoc reference)
             (minde commands)
             (minde command-catalog))

(define %github-blob-base
  "https://github.com/9s-l-s9/minde/blob/main/")

(define public-modules
  '((minde windows)
    (minde frames)
    (minde groups)
    (minde layouts)
    (minde input)
    (minde commands)
    (minde hooks)
    (minde status)))

(define (one-line text)
  (string-join (string-tokenize text) " "))

(define (markdown text)
  (string-join (string-split (one-line text) #\|) "\\|"))

;; SRFI-9 accessors are syntax transformers, and exported constants are
;; values; neither can carry a procedure docstring. Their defining module
;; may keep an adjacent, quoted %api-binding-documentation alist as the
;; source of truth -- fed into the scan via autodoc's on-form hook.
(define (register-documentation-metadata! scan module-name form path line)
  (when (and module-name
             (pair? form)
             (memq (car form) '(define define-public))
             (> (length form) 2)
             (eq? (cadr form) '%api-binding-documentation)
             (pair? (caddr form))
             (eq? (caaddr form) 'quote)
             (list? (car (cdaddr form))))
    (for-each
     (lambda (entry)
       (unless (and (pair? entry) (symbol? (car entry)) (string? (cdr entry)))
         (error "invalid %api-binding-documentation entry" entry))
       (register-documentation! scan module-name (car entry) (cdr entry))
       (register-documentation! scan #f (car entry) (cdr entry)))
     (car (cdaddr form)))))

(define (command-for name)
  (command-ref name))

(define (binding-demo module-name name value info)
  (let ((command (command-for name)))
    (string-append "`" (if command (symbol->string (command-demo-id command)) "non-visual") "`")))

(define (documentation-fallback module-name name value)
  (let ((command (command-for name)))
    (and command (command-documentation command))))

(define (documented? module-name name value info)
  (or (source-info-documentation info)
      (and (procedure? value) (procedure-documentation value))
      (command-for name)))

(register-builtin-command-schemas!)

;; Re-run the same source scan generate-api-reference does internally, only
;; to compute the missing-docstring count below -- cheap (a handful of
;; small files) and keeps that count using the exact same documented?
;; rule the table itself uses via (autodoc reference)'s own fallback to
;; command-catalog documentation (documented? mirrors, rather than reuses,
;; that fallback: (autodoc reference) has no notion of a command catalog).
(define scan
  (scan-source-files (scan-tree "scheme")
                     #:on-form register-documentation-metadata!))

(define (module-bindings module-name)
  (sort
   (module-map (lambda (name variable) (cons name (variable-ref variable)))
               (resolve-interface module-name))
   (lambda (l r) (string<? (symbol->string (car l)) (symbol->string (car r))))))

(define all-bindings
  (append-map (lambda (module-name)
                (map (lambda (binding) (cons module-name binding))
                     (module-bindings module-name)))
              public-modules))

(define missing-count
  (count (lambda (entry)
           (let* ((module-name (car entry)) (name (cadr entry)) (value (cddr entry))
                  (info (lookup-source-info scan module-name name)))
             (not (documented? module-name name value info))))
         all-bindings))

(display "# Generated Scheme API reference\n\n")
(display "<!-- Generated by scripts/generate-api-reference.scm; do not edit. -->\n\n")
(format #t "This inventory enumerates the live exports of all eight public modules. It currently contains **~a bindings**; **~a** still lack a source docstring, non-procedure metadata, or command-catalog description. Missing descriptions remain visible as release debt rather than being omitted.\n\n"
        (length all-bindings) missing-count)

(display (generate-api-reference
          #:modules public-modules
          #:source-directory "scheme"
          #:repo-blob-prefix %github-blob-base
          #:title #f
          #:extra-columns (list (cons "Demonstration" binding-demo))
          #:missing-docstring-text "No Guile docstring is attached."
          #:documentation-fallback documentation-fallback
          #:on-form register-documentation-metadata!))

(display "## Registered commands\n\n")
(display "| Command | Arguments | Category | Summary | Demo ID |\n")
(display "|---|---|---|---|---|\n")
(for-each
 (lambda (name)
   (let ((command (command-ref name)))
     (format #t "| `~a` | `~s` | `~a` | ~a | `~a` |\n"
             name
             (command-arguments command)
             (command-category command)
             (markdown (command-summary command))
             (command-demo-id command))))
 (command-names))
