#!/bin/sh
exec guile --no-auto-compile -L scheme -s "$0" "$@"
!#
;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Emit the machine-readable API catalog from the live introspection source.
;;;
;;; The catalog is produced by the very same `describe-api' procedure that
;;; answers the IPC socket at runtime (scheme/api-introspect.scm), so the file
;;; under doc/generated/ and the live reply cannot drift. A `.scm' artifact is
;;; chosen over JSON deliberately: describe-api already returns re-readable
;;; Scheme data honoring the writable-data guarantee, so `write' emits it with
;;; no second serializer to keep in step; the doc-drift gate compares it with
;;; `diff' exactly like the other generated documents.

(use-modules (srfi srfi-1)
             (srfi srfi-13)
             (minde commands)
             (minde command-catalog))

;; describe-api is a plain top-level procedure, not a module export; load its
;; defining file the way init.scm and the headless test do.
(load-from-path "api-introspect.scm")

;; Populate the command registry with the built-in catalog schemas so the
;; commands section is complete without a running compositor.
(register-builtin-command-schemas!)

(define catalog (describe-api))

(define (write-section port label entries)
  (format port "  (~a" label)
  (if (null? entries)
      (display ")" port)
      (begin
        (for-each (lambda (entry) (format port "~%   ~s" entry)) entries)
        (display ")" port)))
  (newline port))

(display ";; Generated by scripts/generate-api-catalog.scm from describe-api; do not edit.\n")
(display ";; The runtime IPC reply to (describe-api) is produced from the same source.\n")
(display "(api-catalog\n")
(display "  (schema-version 1)\n")
(for-each
 (lambda (section)
   (write-section (current-output-port) (car section) (cdr section)))
 catalog)
(display ")\n")
