;; SPDX-License-Identifier: GPL-3.0-or-later
;; Versioned, deterministic inputs for scripts/capture-demos.
(minde-demo-scenarios
 (version 1)
 (scenario (id group-next)
           (title "Focus the next group")
           (trigger "C-t g n")
           (input ("ctrl+t" "g" "n"))
           (setup "(switch-to-group! 0)")
           (action "(switch-to-next-group!)")
           (cleanup "(switch-to-group! 0)"))
 (scenario (id group-previous)
           (title "Focus the previous group")
           (trigger "C-t g p")
           (input ("ctrl+t" "g" "p"))
           (setup "(switch-to-group! 0)")
           (action "(switch-to-previous-group!)")
           (cleanup "(switch-to-group! 0)"))
 (scenario (id group-last)
           (title "Return to the last group")
           (trigger "C-t g o")
           (input ("ctrl+t" "g" "o"))
           (setup "(begin (switch-to-group! 1) (switch-to-group! 0))")
           (action "(switch-to-last-group!)")
           (cleanup "(switch-to-group! 0)"))
 (scenario (id frame-next)
           (title "Focus the next frame")
           (trigger "command: focus-next-frame!")
           (input ())
           (setup "(begin (collapse-to-one-frame!) (split-frame-horizontal!))")
           (action "(focus-next-frame!)")
           (cleanup "(collapse-to-one-frame!)"))
 (scenario (id frame-previous)
           (title "Focus the previous frame")
           (trigger "command: focus-previous-frame!")
           (input ())
           (setup "(begin (collapse-to-one-frame!) (split-frame-horizontal!))")
           (action "(focus-previous-frame!)")
           (cleanup "(collapse-to-one-frame!)"))
 (scenario (id window-next)
           (title "Focus the next group window")
           (trigger "C-t n")
           (input ("ctrl+t" "n"))
           (setup "(collapse-to-one-frame!)")
           (action "(focus-next-window!)")
           (cleanup "#t"))
 (scenario (id window-previous)
           (title "Focus the previous group window")
           (trigger "C-t w p")
           (input ("ctrl+t" "w" "p"))
           (setup "(collapse-to-one-frame!)")
           (action "(focus-previous-window!)")
           (cleanup "#t"))
 (scenario (id window-pull)
           (title "Pull the next hidden window")
           (trigger "C-t p")
           (input ("ctrl+t" "p"))
           (setup "(collapse-to-one-frame!)")
           (action "(pull-hidden-next!)")
           (cleanup "#t"))
 (scenario (id frame-split-horizontal)
           (title "Split the frame into columns")
           (trigger "C-t f h")
           (input ("ctrl+t" "f" "h"))
           (setup "(collapse-to-one-frame!)")
           (action "(split-frame-horizontal!)")
           (cleanup "(collapse-to-one-frame!)"))
 (scenario (id frame-split-vertical)
           (title "Split the frame into rows")
           (trigger "C-t f v")
           (input ("ctrl+t" "f" "v"))
           (setup "(collapse-to-one-frame!)")
           (action "(split-frame-vertical!)")
           (cleanup "(collapse-to-one-frame!)"))
 (scenario (id frame-remove-split)
           (title "Remove the current split")
           (trigger "C-t f c")
           (input ("ctrl+t" "f" "c"))
           (setup "(begin (collapse-to-one-frame!) (split-frame-horizontal!))")
           (action "(remove-split!)")
           (cleanup "(collapse-to-one-frame!)"))
 (scenario (id frame-clear)
           (title "Clear the current frame")
           (trigger "C-t f e")
           (input ("ctrl+t" "f" "e"))
           (setup "(collapse-to-one-frame!)")
           (action "(clear-current-frame!)")
           (cleanup "(focus-next-window!)"))
 (scenario (id frame-collapse)
           (title "Collapse the head to one frame")
           (trigger "C-t f o")
           (input ("ctrl+t" "f" "o"))
           (setup "(begin (collapse-to-one-frame!) (split-frame-horizontal!))")
           (action "(collapse-to-one-frame!)")
           (cleanup "#t"))
 (scenario (id head-next)
           (title "Focus the next output head")
           (trigger "command: focus-next-head!")
           (input ())
           (setup "(handle-heads-change! '((0 0 0 640 800) (1 640 0 640 800)))")
           (action "(focus-next-head!)")
           (cleanup "(handle-heads-change! '((0 0 0 1280 800)))"))
 (scenario (id head-last)
           (title "Return to the last output head")
           (trigger "command: focus-last-head!")
           (input ())
           (setup "(begin (handle-heads-change! '((0 0 0 640 800) (1 640 0 640 800))) (focus-next-head!))")
           (action "(focus-last-head!)")
           (cleanup "(handle-heads-change! '((0 0 0 1280 800)))"))
 (scenario (id configuration-reload)
           (title "Validate and reload configuration")
           (trigger "C-t s r")
           (input ("ctrl+t" "s" "r"))
           (setup "#t")
           (action "(reload-configuration!)")
           (cleanup "#t")))
