;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Client-only IPC, JSON projection, polling, and interactive REPL.
(define-module (minde control-client)
  #:use-module (ice-9 match)
  #:use-module (ice-9 rdelim)
  #:use-module (rnrs bytevectors)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-13)
  #:use-module (minde control-json)
  #:export (control-client-main ipc-request read-one-datum build-control-expression
            emit-reply wait-for-action watch-desktop))

(define %max-reply-bytes (* 1024 1024))
(define %max-request-bytes (* 64 1024))
(define (milliseconds)
  (quotient (* (get-internal-real-time) 1000) internal-time-units-per-second))
(define (read-one-datum text)
  (catch #t
    (lambda ()
      (with-fluids ((read-eval? #f))
        (call-with-input-string text
          (lambda (port)
            (let ((value (read port)))
              (when (or (eof-object? value) (not (eof-object? (read port))))
                (throw 'client-error "expected exactly one Scheme datum"))
              value)))))
    (lambda (key . args)
      (if (eq? key 'client-error) (apply throw key args)
          (throw 'client-error "invalid Scheme datum")))))
(define (scheme-string datum)
  (call-with-output-string (lambda (port) (write datum port))))
(define (transport-error code message sent?)
  `(error ,code () ,message ""
          ((stage . transport) (outcome . ,(if sent? 'unknown 'not-started))
           (execution-started? . ,(if sent? 'unknown #f))
           (execution-completed? . #f)
           (effects-may-have-occurred? . ,(and sent? #t)))))
(define (wait-ready sock write? deadline)
  (let ((remaining (- deadline (milliseconds))))
    (when (<= remaining 0) (throw 'transport-failure 'timeout "IPC deadline exceeded"))
    (let ((ready (select (if write? '() (list sock))
                         (if write? (list sock) '()) '()
                         (quotient remaining 1000) (* (modulo remaining 1000) 1000))))
      (unless (pair? (list-ref ready (if write? 1 0)))
        (throw 'transport-failure 'timeout "IPC deadline exceeded")))))
(define (would-block? arguments)
  (memv (system-error-errno arguments) (list EAGAIN EWOULDBLOCK EINPROGRESS EINTR)))
(define* (ipc-request path expression #:key (timeout-ms 2000))
  "One bounded request/response exchange, with no automatic retries. A lost
reply after sending is an unknown outcome; timeout does not cancel evaluation."
  (let ((sock #f) (sent? #f) (deadline (+ (milliseconds) timeout-ms)))
    (catch #t
      (lambda ()
        (let* ((directory (dirname path)) (st (stat directory))
               (request (string->utf8 expression)))
          (unless (and (eq? (stat:type st) 'directory)
                       (= (stat:uid st) (geteuid))
                       (zero? (logand (stat:perms st) #o077)))
            (throw 'transport-failure 'unsafe-runtime-directory
                   "runtime directory must be private and owned by the calling user"))
          (when (> (bytevector-length request) %max-request-bytes)
            (throw 'transport-failure 'request-too-large "request exceeds 64 KiB"))
          (set! sock (socket PF_UNIX SOCK_STREAM 0))
          ;; Guile does not export Linux's MSG_NOSIGNAL on every build.
          ;; This client process reports EPIPE as structured transport failure.
          (sigaction SIGPIPE SIG_IGN)
          (fcntl sock F_SETFL (logior O_NONBLOCK (fcntl sock F_GETFL)))
          (catch 'system-error
            (lambda () (connect sock AF_UNIX path))
            (lambda (key . args)
              (unless (would-block? args) (apply throw key args))
              (wait-ready sock #t deadline)
              (unless (zero? (getsockopt sock SOL_SOCKET SO_ERROR))
                (throw 'transport-failure 'connection-failed "could not connect to IPC socket"))))
          (let send-loop ((offset 0))
            (when (< offset (bytevector-length request))
              (wait-ready sock #t deadline)
              (let* ((remaining (- (bytevector-length request) offset))
                     (bytes (make-bytevector remaining)))
                (bytevector-copy! request offset bytes 0 remaining)
                ;; Once send is attempted, conservatively allow partial delivery.
                (set! sent? #t)
                (let ((n (catch 'system-error
                           (lambda () (send sock bytes))
                           (lambda (key . args)
                             (if (would-block? args) 0 (apply throw key args))))))
                  (send-loop (+ offset n))))))
          (shutdown sock 1)
          (let ((buffer (make-bytevector 8192)))
            (let receive-loop ((chunks '()) (total 0))
              (wait-ready sock #f deadline)
              (let ((n (catch 'system-error
                         (lambda () (recv! sock buffer))
                         (lambda (key . args)
                           (if (would-block? args) -1 (apply throw key args))))))
                (cond
                 ((negative? n) (receive-loop chunks total))
                 ((zero? n)
                  (close sock) (set! sock #f)
                  (let ((bytes (make-bytevector total)))
                    (let copy ((chunks (reverse chunks)) (offset 0))
                      (unless (null? chunks)
                        (let ((n (bytevector-length (car chunks))))
                          (bytevector-copy! (car chunks) 0 bytes offset n)
                          (copy (cdr chunks) (+ offset n)))))
                    (let ((reply (catch #t
                                   (lambda () (read-one-datum (utf8->string bytes)))
                                   (lambda _ (throw 'transport-failure 'invalid-reply
                                                    "missing, incomplete, or invalid IPC reply")))))
                      (unless (and (list? reply)
                                   (or (and (= (length reply) 2) (eq? (car reply) 'ok))
                                       (and (>= (length reply) 5) (eq? (car reply) 'error)
                                            (string? (list-ref reply 3))
                                            (string? (list-ref reply 4))
                                            (or (= (length reply) 5)
                                                (and (list? (list-ref reply 5))
                                                     (every (lambda (entry)
                                                              (and (pair? entry) (symbol? (car entry))))
                                                            (list-ref reply 5)))))))
                        (throw 'transport-failure 'invalid-reply "invalid IPC envelope"))
                      reply)))
                 ((> (+ total n) %max-reply-bytes)
                  (throw 'transport-failure 'reply-too-large "IPC reply exceeds 1 MiB"))
                 (else
                  (let ((chunk (make-bytevector n)))
                    (bytevector-copy! buffer 0 chunk 0 n)
                    (receive-loop (cons chunk chunks) (+ total n))))))))))
      (lambda (key . args)
        (when sock (false-if-exception (close sock)))
        (if (eq? key 'transport-failure)
            (transport-error (car args) (cadr args) sent?)
            (transport-error 'connection-failed
                             "IPC connection failed; inspect receipt before retrying any action"
                             sent?))))))

(define (request-before-deadline path expression deadline)
  (let ((remaining (- deadline (milliseconds))))
    (if (positive? remaining)
        (ipc-request path expression #:timeout-ms remaining)
        (transport-error 'timeout "IPC deadline exceeded before sending request" #f))))

(define (quote-datum datum) (list 'quote datum))
(define (option options name default) (let ((entry (assoc name options))) (if entry (cdr entry) default)))
(define (optional-keywords options)
  (append (if (option options "--session" #f) (list #:session (option options "--session" #f)) '())
          (if (option options "--revision" #f) (list #:if-revision (option options "--revision" #f)) '())
          (if (option options "--request-id" #f) (list #:request-id (option options "--request-id" #f)) '())))
(define (build-control-expression command arguments options)
  "Build code from typed datums and quoted literals, never interpolate strings."
  (match (cons command arguments)
    (("eval" expression) expression)
    (("capabilities") "(capabilities)")
    (("help" name) (scheme-string `(describe-action ',(string->symbol name))))
    (("search" query) (scheme-string `(search-actions ,query)))
    (("query" "desktop") "(desktop-snapshot)")
    (("query" "windows") "(let ((s (desktop-snapshot))) (list (cons 'windows (assq-ref s 'windows))))")
    (("request") "(new-action-request)")
    (("call" name arguments)
     (scheme-string (append (list 'perform-action! (quote-datum (string->symbol name))
                                 (quote-datum (read-one-datum arguments)))
                            (optional-keywords options))))
    (("events-since" sequence)
     (let ((number (string->number sequence)))
       (unless (and (exact-integer? number) (>= number 0)) (throw 'client-error "sequence must be a nonnegative integer"))
       (scheme-string `(events-since ,number ,@(if (option options "--session" #f)
                                                 (list #:session (option options "--session" #f)) '())))))
    (_ (throw 'client-error "invalid command or arguments; run mindectl --help"))))
(define (reply-failed? reply kind)
  (or (eq? (car reply) 'error)
      (and (eq? kind 'action) (eq? (assq-ref (cadr reply) 'status) 'error))))
(define* (emit-reply reply kind #:key (mode 'human) (backtrace? #f))
  "Machine modes keep errors on stdout; diagnostics never contaminate it."
  (cond
   ((eq? mode 'json)
    (display (control-json (if (eq? (car reply) 'error) reply (cadr reply))
                           (if (eq? (car reply) 'error) 'ipc-error kind))) (newline))
   ((eq? mode 'scheme) (write reply) (newline))
   ((eq? (car reply) 'ok) (write (cadr reply)) (newline))
   (else
    (format (current-error-port) "mindectl: ~a: ~a~%" (cadr reply) (list-ref reply 3))
    (when (and backtrace? (not (string-null? (list-ref reply 4))))
      (display (list-ref reply 4) (current-error-port)))))
  (cond ((and (eq? (car reply) 'error) (> (length reply) 5)
              (eq? (assq-ref (list-ref reply 5) 'stage) 'transport)) 3)
        ((reply-failed? reply kind) 1) (else 0)))
(define* (wait-for-action path id #:key (session #f) (timeout-ms 10000))
  "Poll receipt state in the client. Expiry stops observation, never the action."
  (let ((deadline (+ (milliseconds) timeout-ms)))
    (let loop ()
      (let* ((remaining (max 1 (- deadline (milliseconds))))
             (reply (ipc-request path (scheme-string `(action-status ,id ,@(if session (list #:session session) '())))
                                 #:timeout-ms (min 2000 remaining))))
        (cond
         ((eq? (car reply) 'error) reply)
         ((not (memq (assq-ref (cadr reply) 'status) '(ready pending))) reply)
         ((>= (milliseconds) deadline)
          (transport-error 'observation-timeout "wait deadline exceeded; action may still complete" #t))
         (else (usleep (* 1000 (min 50 (max 1 (- deadline (milliseconds)))))) (loop)))))))

(define* (watch-desktop path #:key (mode 'scheme) (count #f) (interval-ms 200))
  "Emit a snapshot, then journal pages. Snapshot's cursor is the handoff;
advance to each page's watermark, including empty redacted pages. Read-only
reconnection always obtains a fresh snapshot, never retries an action."
  (define (publish reply kind)
    (cond ((eq? mode 'json)
           (display (string-append "{\"type\":\"" (symbol->string kind)
                                   "\",\"data\":" (control-json (cadr reply) kind) "}"))
           (newline))
          (else (write `(ok ((type . ,kind) (data . ,(cadr reply))))) (newline)))
    (force-output))
  (let loop ((session #f) (cursor #f) (emitted 0))
    (if (and count (>= emitted count)) 0
        (let* ((snapshot? (not session))
               (reply (ipc-request path
                                   (if snapshot? "(desktop-snapshot)"
                                       (scheme-string `(events-since ,cursor #:session ,session))))))
          (cond
           ((eq? (car reply) 'error)
            ;; A stream reconnect is safe because both operations only inspect.
            (format (current-error-port) "mindectl watch: ~a; reconnecting~%" (cadr reply))
            (usleep (* interval-ms 1000))
            (loop #f #f emitted))
           (snapshot?
            (publish reply 'desktop)
            (loop (assq-ref (cadr reply) 'session)
                  (assq-ref (cadr reply) 'event-sequence) (+ emitted 1)))
           ((or (assq-ref (cadr reply) 'gap)
                (not (equal? session (assq-ref (cadr reply) 'session))))
            (loop #f #f emitted))
           (else
            (publish reply 'events)
            (unless (and count (>= (+ emitted 1) count)) (usleep (* interval-ms 1000)))
            (loop session (assq-ref (cadr reply) 'sequence) (+ emitted 1))))))))

(define (parse-options arguments)
  (let loop ((remaining arguments) (positionals '()) (options '()))
    (match remaining
      (() (values (reverse positionals) options))
      (((or "--machine" "--scheme" "--json" "--backtrace") . rest)
       (loop rest positionals (acons (car remaining) #t options)))
      (((or "--session" "--revision" "--request-id" "--timeout-ms" "--count") value . rest)
       (let* ((name (car remaining))
              (numeric? (member name '("--revision" "--timeout-ms" "--count")))
              (value (if numeric? (string->number value) value)))
         (when (and numeric? (not (and (exact-integer? value) (>= value 0))))
           (throw 'client-error (string-append name " requires a nonnegative integer")))
         (when (and (string=? name "--timeout-ms") (or (= value 0) (> value 3600000)))
           (throw 'client-error "--timeout-ms must be between 1 and 3600000"))
         (when (and (string=? name "--count") (= value 0))
           (throw 'client-error "--count must be positive"))
         (loop rest positionals (acons name value options))))
      ((head . rest)
       (when (string-prefix? "--" head) (throw 'client-error (string-append "unknown or incomplete option: " head)))
       (loop rest (cons head positionals) options)))))
(define (command-kind command args)
  (cond ((string=? command "query") (if (equal? args '("desktop")) 'desktop 'windows))
        ((member command '("call" "wait")) 'action)
        ((string=? command "help") 'description)
        ((string=? command "events-since") 'events)
        ((member command '("capabilities" "search" "request")) (string->symbol command))
        (else 'raw)))
(define (validate-options command options)
  (for-each
   (lambda (entry)
     (let ((name (car entry)))
       (unless (cond
                ((member name '("--session")) (member command '("call" "wait" "events-since")))
                ((member name '("--revision" "--request-id")) (string=? command "call"))
                ((string=? name "--count") (string=? command "watch"))
                ((string=? name "--timeout-ms") (not (member command '("watch" "repl"))))
                (else (not (string=? command "repl"))))
         (throw 'client-error (string-append name " does not apply to " command)))))
   options))
(define (ensure-directory path)
  (unless (file-exists? path)
    (ensure-directory (dirname path))
    (mkdir path #o700)))
(define (repl-input-state source)
  (catch #t
    (lambda ()
      (with-fluids ((read-eval? #f))
        (call-with-input-string source
          (lambda (port)
            (let ((datum (read port)))
              (cond ((eof-object? datum) 'empty)
                    ((eof-object? (read port)) 'complete)
                    (else 'invalid)))))))
    (lambda (key . args)
      (let ((message (scheme-string args)))
        (if (and (eq? key 'read-error)
                 (or (string-contains message "end of input")
                     (string-contains message "unterminated")))
            'incomplete 'invalid)))))
(define (repl path)
  (let* ((interactive? (isatty? (current-input-port)))
         (readline-module (and interactive? (false-if-exception (resolve-interface '(ice-9 readline)))))
         (binding (lambda (name) (and readline-module (module-ref readline-module name))))
         (history (string-append (or (getenv "XDG_STATE_HOME")
                                    (string-append (or (getenv "HOME") "/tmp") "/.local/state"))
                                 "/minde/repl-history"))
         (catalog (ipc-request path "(capabilities)"))
         (names (if (eq? (car catalog) 'ok)
                    (map (lambda (entry) (symbol->string (assq-ref entry 'name)))
                         (assq-ref (cadr catalog) 'actions)) '()))
         (completion (and readline-module ((binding 'make-completion-function)
                                          (append '("desktop-snapshot" "describe-action" "perform-action!"
                                                    "action-status" "new-action-request" ",help" ",quit") names)))))
    (when readline-module
      (false-if-exception ((binding 'read-history) history)))
    (define (next-line prompt)
      (if readline-module
          ((binding 'with-readline-completion-function) completion
           (lambda () ((binding 'readline) prompt)))
          (begin (when interactive? (display prompt) (force-output)) (read-line))))
    (define (remember source)
      (when readline-module
        ((binding 'add-history) source)
        (false-if-exception
         (begin (ensure-directory (dirname history))
                ;; Create with restrictive mode before readline opens it.
                (let ((port (open history (logior O_WRONLY O_CREAT) #o600))) (close port))
                (chmod history #o600)
                ((binding 'write-history) history)))))
    (when interactive?
      (display "Minde remote Scheme REPL. ,help [ACTION], ,quit. Evaluation runs on the compositor thread.\n"))
    (let loop ((source ""))
      (let ((line (next-line (if (string-null? source) "minde> " "... "))))
        (cond
         ((eof-object? line)
          (if (string-null? source) 0
              (begin (format (current-error-port) "mindectl: incomplete Scheme input~%") 2)))
         ((and (string-null? source) (string=? (string-trim-both line) ",quit")) 0)
         ((and (string-null? source)
               (or (string=? line ",help") (string-prefix? ",help " line)))
          (let ((name (string-trim-both (substring line 5))))
            (emit-reply (ipc-request path (if (string-null? name) "(capabilities)"
                                             (scheme-string `(describe-action ',(string->symbol name)))))
                        (if (string-null? name) 'capabilities 'description)))
          (loop ""))
         (else
          (let* ((source (string-append source line "\n"))
                 (parsed (repl-input-state source)))
            (case parsed
              ((empty) (loop ""))
              ((incomplete) (loop source))
              ((invalid) (format (current-error-port) "mindectl: invalid Scheme input~%") (loop ""))
              (else (remember source) (emit-reply (ipc-request path source) 'raw) (loop ""))))))))))

(define (control-client-main arguments)
  "Entry point: PATH followed by the CLI arguments. Returns an exit status."
  (catch #t
    (lambda ()
      (let ((path (car arguments)))
        (call-with-values (lambda () (parse-options (cdr arguments)))
          (lambda (positionals options)
            (when (null? positionals) (throw 'client-error "missing command"))
            (let* ((command (car positionals)) (args (cdr positionals))
                   (mode (cond ((option options "--json" #f) 'json)
                               ((or (option options "--scheme" #f) (option options "--machine" #f)) 'scheme)
                               (else 'human)))
                   (kind (command-kind command args)))
              (validate-options command options)
              (cond
               ((string=? command "watch")
                (unless (null? args) (throw 'client-error "watch accepts no positional arguments"))
                (watch-desktop path #:mode mode #:count (option options "--count" #f)))
               ((string=? command "repl")
                (if (null? args) (repl path) (throw 'client-error "repl accepts no positional arguments")))
               (else
                  (let* ((deadline (+ (milliseconds) (option options "--timeout-ms" 2000)))
                         (expression (and (not (string=? command "wait"))
                                          (build-control-expression command args options)))
                         (allocation (and (string=? command "call")
                                          (not (option options "--request-id" #f))
                                          (request-before-deadline path "(new-action-request)" deadline))))
                    (when (and allocation (eq? (car allocation) 'ok))
                      (let ((receipt (cadr allocation)))
                        (set! options (acons "--request-id" (assq-ref receipt 'request-id) options))
                        (unless (option options "--session" #f)
                          (set! options (acons "--session" (assq-ref receipt 'session) options)))
                        (unless (option options "--revision" #f)
                          (set! options (acons "--revision" (assq-ref receipt 'revision) options)))
                        (set! expression (build-control-expression command args options))))
                    (let ((reply
                           (cond
                            ((and allocation (eq? (car allocation) 'error)) allocation)
                            ((string=? command "wait")
                             (unless (= (length args) 1) (throw 'client-error "wait requires a receipt ID"))
                             (wait-for-action path (car args) #:session (option options "--session" #f)
                                              #:timeout-ms (option options "--timeout-ms" 10000)))
                            (else (request-before-deadline path expression deadline)))))
                      (when (and (string=? command "call") (eq? (car reply) 'error)
                                 (> (length reply) 5) (option options "--request-id" #f))
                        (set! reply (append (take reply 5)
                                            (list (append (list-ref reply 5)
                                                          `((request-id . ,(option options "--request-id" #f))
                                                            (session . ,(option options "--session" #f))))))))
                      (emit-reply reply kind #:mode mode #:backtrace? (option options "--backtrace" #f)))))))))))
    (lambda (key . args)
      (let* ((validation? (memq key '(client-error read-error)))
             (message (if (eq? key 'client-error) (car args)
                          "invalid command arguments or reply"))
             (reply `(error ,(if validation? 'invalid-argument 'client-error) () ,message ""
                            ((stage . ,(if validation? 'validation 'client))
                             (execution-started? . ,(if validation? #f 'unknown))
                             (execution-completed? . #f)
                             (effects-may-have-occurred? . ,(not validation?)))))
             (mode (cond ((member "--json" arguments) 'json)
                         ((or (member "--scheme" arguments) (member "--machine" arguments)) 'scheme)
                         (else 'human))))
        (emit-reply reply 'raw #:mode mode))
      2)))
