;;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Schema-directed JSON projection; arbitrary Scheme data is never guessed.
(define-module (minde control-json)
  #:use-module (srfi srfi-1)
  #:export (control-json raw-scheme-json))

(define (json-string value)
  (call-with-output-string
   (lambda (p)
     (write-char #\" p)
     (string-for-each
      (lambda (c)
        (case c
          ((#\") (display "\\\"" p)) ((#\\) (display "\\\\" p))
          ((#\newline) (display "\\n" p)) ((#\return) (display "\\r" p))
          ((#\tab) (display "\\t" p))
          (else (if (< (char->integer c) 32)
                    (let ((hex (number->string (char->integer c) 16)))
                      (display "\\u" p)
                      (display (make-string (- 4 (string-length hex)) #\0) p)
                      (display hex p))
                    (write-char c p))))) value)
     (write-char #\" p))))
(define (join parts) (string-join parts ","))
(define (array values project)
  (string-append "[" (join (map project (if (vector? values) (vector->list values) values))) "]"))
(define (object fields project)
  (string-append "{" (join (map (lambda (entry)
                                 (string-append (json-string (symbol->string (car entry))) ":"
                                                (project (car entry) (cdr entry)))) fields)) "}"))
(define (raw-scheme-json value)
  "Lossless canonical Scheme fallback. Lists, symbols, exact rationals, etc.
are explicitly tagged, never inferred to be a JSON object or array."
  (cond ((boolean? value) (if value "true" "false"))
        ((string? value) (json-string value))
        ((and (integer? value) (exact? value)) (number->string value))
        ((and (real? value) (inexact? value) (finite? value)) (number->string value))
        (else (string-append "{\"$scheme\":"
                             (json-string (call-with-output-string (lambda (p) (write value p)))) "}"))))
(define (scalar value)
  (cond ((eq? value 'null) "null")
        ((symbol? value) (json-string (symbol->string value)))
        (else (raw-scheme-json value))))
(define (type-json value)
  (if (list? value) (array value type-json) (scalar value)))
(define (record value kind)
  (if (not value) "false"
      (object value (lambda (key item) (field-json kind key item)))))
(define (field-json kind key value)
  (cond
   ((and (eq? kind 'desktop) (memq key '(groups windows outputs)))
    (array value (lambda (item) (record item (case key ((groups) 'group) ((windows) 'window) (else 'output))))))
   ((and (eq? kind 'group) (eq? key 'frames)) (array value (lambda (item) (record item 'frame))))
   ((and (eq? kind 'group) (eq? key 'trees)) (array value (lambda (item) (record item 'tree))))
   ((and (eq? kind 'desktop) (eq? key 'layout-definitions))
    (array value (lambda (item) (record item 'layout-definition))))
   ((and (eq? kind 'window) (eq? key 'locations)) (array value (lambda (item) (record item 'location))))
   ((and (eq? kind 'windows) (eq? key 'windows)) (array value (lambda (item) (record item 'window))))
   ((and (eq? kind 'capabilities) (eq? key 'actions)) (array value (lambda (item) (record item 'summary))))
   ((and (eq? kind 'description) (eq? key 'parameters))
    (if value (array value (lambda (item) (record item 'parameter))) "false"))
   ((and (eq? kind 'parameter) (eq? key 'type)) (type-json value))
   ((and (eq? kind 'parameter) (memq key '(default enum)))
    (if (eq? key 'enum) (array value raw-scheme-json) (raw-scheme-json value)))
   ((and (eq? kind 'description) (memq key '(examples preconditions result-schema)))
    (raw-scheme-json value))
   ((and (eq? kind 'events) (eq? key 'events)) (array value (lambda (item) (record item 'event))))
   ((and (eq? kind 'event) (eq? key 'arguments)) (array value raw-scheme-json))
   ((and (eq? kind 'action) (eq? key 'error)) (record value 'action-error))
   ((and (eq? kind 'action) (eq? key 'value)) (if (eq? value 'null) "null" (raw-scheme-json value)))
   ((and (eq? kind 'action-error) (eq? key 'details)) (raw-scheme-json value))
   ((memq key '(geometry float-geometry layouts schema-types schema-constructors effects arguments))
    (cond ((eq? value 'null) "null")
          ((or (vector? value) (list? value)) (array value scalar))
          (else (scalar value))))
   ((and (eq? kind 'frame) (eq? key 'windows)) (array value scalar))
   (else (scalar value))))
(define (control-json value kind)
  "Project known KIND's versioned schema. KIND raw uses lossless Scheme tags.
Action value and extension fields containing compound data remain tagged."
  (case kind
    ((raw) (raw-scheme-json value))
    ((search) (array value (lambda (item) (record item 'summary))))
    ((ipc-error)
     (string-append "{\"error\":{\"code\":" (scalar (cadr value))
                    ",\"arguments\":" (raw-scheme-json (caddr value))
                    ",\"message\":" (json-string (list-ref value 3))
                    ",\"metadata\":"
                    (if (> (length value) 5) (record (list-ref value 5) 'metadata) "{}") "}}"))
    (else (record value kind))))
